{{- $fullName := include "template-app.fullname" $ -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $fullName }}-hpa
  labels:
    {{- include "template-app.labels" $ | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $fullName }}
  minReplicas: {{ .Values.replicaCount }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  {{- range .Values.hpa.metrics }}
  - type: {{ .type }}
    resource:
      name: {{ .name }}
      target:
        type: {{ .target.type }}
        averageUtilization: {{ .target.averageUtilization }}
  {{- end }}
