{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: {{ .Values.name }}-ingress
spec:
  rules:
  - http:
      paths:
        - backend:
            serviceName: {{ include "template-app.name" . }}
            servicePort: {{ .Values.service.port }}
          path: /
{{- end -}}

